# Permalinks
permalink:      /:year-:month/:title

# Setup
title:          From All Fifty
paginate:       8
baseurl:        ""
url:            "https://www.fromallfifty.com"
description:    Perspectives from progressive leaders across the country.

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         From All Fifty
  url:          https://www.fromallfifty.com
  email:        contact@fromallfifty.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/CentsforChange/tale

# Gems
gems:
  - jekyll-paginate
